analyzer:
  errors:
    non_constant_identifier_names: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    one_member_abstracts: false
